export const CATEGORIES = {
  VIDEO: "Vídeo",
  AUDIO: "Audio",
  EDIT: "Edición",
  SOCIAL: "Redes Sociales",
  IMAGE: "Imágenes",
  TOOLS: "Herramientas",
  FILTROS: "Filtros",
  EFECTOS: "Efectos",
};

const presets = [
  {
    title: "Convertir video a MP4",
    description: "Convierte el video a formato MP4 con codec H.264.",
    category: CATEGORIES.VIDEO,
  },
  {
    title: "Convertir video a WebM",
    description: "Convierte el video a formato WebM optimizado para web.",
    category: CATEGORIES.VIDEO,
  },
  {
    title: "Convertir video a AVI",
    description: "Convierte el video a formato AVI.",
    category: CATEGORIES.VIDEO,
  },
  {
    title: "Convertir video a MKV",
    description: "Convierte el video a formato MKV sin pérdida de calidad.",
    category: CATEGORIES.VIDEO,
  },
  {
    title: "Convertir video a MOV",
    description: "Convierte el video a formato MOV (QuickTime).",
    category: CATEGORIES.VIDEO,
  },
  {
    title: "Extraer audio a MP3",
    description: "Extrae el audio del video y lo guarda en formato MP3.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Extraer audio a WAV",
    description: "Extrae el audio del video a formato WAV sin compresión.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Extraer audio a AAC",
    description: "Extrae el audio del video a formato AAC de alta calidad.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Extraer audio a OGG",
    description: "Extrae el audio del video a formato OGG Vorbis.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Extraer audio a FLAC",
    description: "Extrae el audio en formato FLAC (alta fidelidad sin pérdida).",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Eliminar audio del video",
    description: "Elimina completamente la pista de audio del video.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Normalizar audio",
    description: "Ajusta el volumen del audio a un nivel estándar.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Aumentar volumen del audio",
    description: "Incrementa el volumen del audio del video.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Reducir volumen del audio",
    description: "Disminuye el volumen del audio del video.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Reducir ruido de audio",
    description: "Elimina o reduce el ruido de fondo del audio.",
    category: CATEGORIES.AUDIO,
  },
  {
    title: "Comprimir video",
    description: "Reduce el tamaño del archivo manteniendo calidad aceptable.",
    category: CATEGORIES.VIDEO,
  },
  {
    title: "Comprimir video al 50%",
    description: "Reduce el tamaño del video aproximadamente a la mitad.",
    category: CATEGORIES.VIDEO,
  },
  {
    title: "Cambiar resolución a 1080p",
    description: "Cambia la resolución del video a 1920x1080 (Full HD).",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar resolución a 720p",
    description: "Cambia la resolución del video a 1280x720 (HD).",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar resolución a 480p",
    description: "Cambia la resolución del video a 854x480 (SD).",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar resolución a 4K",
    description: "Escala el video a resolución 4K (3840x2160).",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Rotar video 90° a la derecha",
    description: "Rota el video 90 grados en sentido horario.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Efecto espejo",
    description: "Duplicar vídeo con efecto espejo.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Rotar video 90° a la izquierda",
    description: "Rota el video 90 grados en sentido antihorario.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Rotar video 180°",
    description: "Voltea el video completamente (180 grados).",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Voltear video horizontalmente",
    description: "Crea un efecto espejo horizontal del video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Voltear video verticalmente",
    description: "Voltea el video de arriba a abajo.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Extraer fotogramas como imágenes",
    description: "Extrae todos los fotogramas del video como imágenes JPG.",
    category: CATEGORIES.IMAGE,
  },
  {
    title: "Extraer 1 fotograma por segundo",
    description: "Extrae una imagen por cada segundo de video.",
    category: CATEGORIES.IMAGE,
  },
  {
    title: "Capturar miniatura del video",
    description: "Extrae una imagen del primer fotograma como miniatura.",
    category: CATEGORIES.IMAGE,
  },
  {
    title: "Crear GIF del video",
    description: "Convierte el video completo a formato GIF animado.",
    category: CATEGORIES.IMAGE,
  },
  {
    title: "Crear GIF de los primeros 5 segundos",
    description: "Convierte los primeros 5 segundos del video a GIF.",
    category: CATEGORIES.IMAGE,
  },
  {
    title: "Acelerar video 2x",
    description: "Acelera la velocidad del video al doble.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Ralentizar video 0.5x",
    description: "Reduce la velocidad del video a la mitad (cámara lenta).",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar velocidad a 1.5x",
    description: "Acelera el video a 1.5 veces su velocidad original.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar FPS a 30",
    description: "Cambia la tasa de fotogramas por segundo a 30 fps.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar FPS a 60",
    description: "Cambia la tasa de fotogramas por segundo a 60 fps.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Recortar primeros 10 segundos",
    description: "Elimina los primeros 10 segundos del video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Recortar últimos 10 segundos",
    description: "Elimina los últimos 10 segundos del video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Extraer segmento específico",
    description: "Extrae una porción del video entre dos tiempos específicos.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Convertir a blanco y negro",
    description: "Elimina el color y convierte el video a escala de grises.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Ajustar brillo del video",
    description: "Aumenta o disminuye el brillo del video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Aclarar video oscuro",
    description: "Mejora la visibilidad en videos grabados con poca luz.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Ajustar contraste del video",
    description: "Modifica el contraste para mejorar la definición.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Ajustar saturación del video",
    description: "Aumenta o reduce la intensidad de los colores.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Aplicar efecto sepia",
    description: "Aplica un filtro sepia de tonos cálidos al video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Invertir colores del video",
    description: "Invierte todos los colores creando un efecto negativo.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Difuminar/Desenfocar video",
    description: "Aplica un efecto de desenfoque a todo el video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Aumentar nitidez del video",
    description: "Mejora la nitidez y los detalles del video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Añadir efecto vignette",
    description: "Oscurece los bordes del video creando un efecto de viñeta.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Estabilizar video",
    description: "Reduce las vibraciones y estabiliza el video.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Cambiar bitrate a alta calidad",
    description: "Aumenta el bitrate para mejorar la calidad del video.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Cambiar bitrate a baja calidad",
    description: "Reduce el bitrate para archivos más pequeños.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Cambiar codec a H.265/HEVC",
    description: "Recodifica el video con codec H.265 para mejor compresión.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Cambiar codec a VP9",
    description: "Recodifica el video con codec VP9 (ideal para web).",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Recortar/Crop al centro",
    description: "Recorta el video manteniendo centrado el contenido.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar relación de aspecto a 16:9",
    description: "Ajusta el video a relación de aspecto 16:9.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar relación de aspecto a 4:3",
    description: "Ajusta el video a relación de aspecto 4:3.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Cambiar relación de aspecto a 1:1 (cuadrado)",
    description: "Convierte el video a formato cuadrado para redes sociales.",
    category: CATEGORIES.SOCIAL,
  },
  {
    title: "Cambiar relación de aspecto a 9:16 (vertical)",
    description: "Convierte el video a formato vertical para móviles.",
    category: CATEGORIES.SOCIAL,
  },
  {
    title: "Añadir padding negro",
    description:
      "Añade bordes negros para ajustar la relación de aspecto sin recortar.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Reproducir video al revés",
    description: "Invierte la reproducción del video de fin a inicio.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Crear bucle del video",
    description: "Repite el video un número determinado de veces.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Extraer solo el primer minuto",
    description: "Extrae únicamente el primer minuto del video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Desentrelazar video",
    description: "Elimina el entrelazado de videos antiguos o de TV.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Optimizar para Instagram",
    description:
      "Optimiza el video para subirlo a Instagram (formato y tamaño).",
    category: CATEGORIES.SOCIAL,
  },
  {
    title: "Optimizar para YouTube",
    description: "Optimiza el video con los mejores ajustes para YouTube.",
    category: CATEGORIES.SOCIAL,
  },
  {
    title: "Optimizar para TikTok",
    description: "Ajusta el video al formato vertical óptimo para TikTok.",
    category: CATEGORIES.SOCIAL,
  },
  {
    title: "Optimizar para Twitter/X",
    description: "Comprime y ajusta el video para cumplir límites de Twitter.",
    category: CATEGORIES.SOCIAL,
  },
  {
    title: "Reducir a menos de 25 MB",
    description: "Comprime el video para que pese menos de 25 MB.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Reducir a menos de 100 MB",
    description: "Comprime el video para que pese menos de 100 MB.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Eliminar metadata del video",
    description: "Elimina todos los metadatos del archivo de video.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Añadir fade in al inicio",
    description: "Añade un fundido de entrada al comienzo del video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Añadir fade out al final",
    description: "Añade un fundido de salida al final del video.",
    category: CATEGORIES.EDIT,
  },
  {
    title: "Extraer subtítulos del video",
    description: "Extrae los subtítulos incrustados a un archivo separado.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Eliminar subtítulos del video",
    description: "Remueve todas las pistas de subtítulos del video.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Limpiar pistas (Mantener solo Video/Audio)",
    description: "Elimina todas las pistas de subtítulos y metadatos extras.",
    category: CATEGORIES.TOOLS,
  },
  {
    title: "Espejo horizontal",
    description: "Duplica el vídeo con una mitad en espejo.",
    filter: "split[left][right];[right]hflip[right];[left][right]hstack",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Colores psicodélicos",
    description: "Cambia tonos y aumenta saturación.",
    filter: "hue=h=90:s=2",
    category: CATEGORIES.FILTROS,
  },
  {
    title: "Vídeo al revés",
    description: "Reproduce el vídeo hacia atrás.",
    filter: "reverse",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Vídeo y audio al revés",
    description: "Efecto mensaje oculto.",
    filter: "[0:v]reverse[v];[0:a]areverse[a]",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Cámara lenta",
    description: "Hace el vídeo 4 veces más lento.",
    filter: "setpts=4*PTS",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Cámara rápida",
    description: "Acelera el vídeo 4 veces.",
    filter: "setpts=0.25*PTS",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Zoom infinito",
    description: "Zoom progresivo tipo sueño.",
    filter: "zoompan=z='zoom+0.001'",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Dibujo de bordes",
    description: "Convierte el vídeo en líneas.",
    filter: "edgedetect",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "VHS antiguo",
    description: "Ruido y look de cinta vieja.",
    filter: "noise=alls=20:allf=t,eq=contrast=1.2:brightness=-0.05",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Glitch RGB",
    description: "Separación de canales de color.",
    filter: "rgbashift=rh=10:bh=-10",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Glitch extremo",
    description: "Distorsión digital agresiva.",
    filter: "noise=alls=50:allf=t+u,chromashift=cbh=5:crh=-5",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Pixel art",
    description: "Convierte vídeo en estilo videojuego retro.",
    filter: "scale=80:-1,scale=iw*10:ih*10:flags=neighbor",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Negativo",
    description: "Invierte los colores.",
    filter: "negate",
    category: CATEGORIES.FILTROS,
  },
  {
    title: "Película antigua",
    description: "Aspecto vintage con ruido.",
    filter: "noise=alls=20,curves=vintage",
    category: CATEGORIES.FILTROS,
  },
  {
    title: "Terremoto",
    description: "La imagen vibra.",
    filter: "crop=in_w-20:in_h-20:10+10*sin(t*20):10+10*cos(t*20)",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Efecto agua",
    description: "Deforma la imagen como ondas.",
    filter: "geq='p(X+10*sin(Y/10+t),Y)':lum_expr='lum(X,Y)'",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Mosaico 4 vídeos",
    description: "Duplica el vídeo en cuatro paneles.",
    filter: "tile=2x2",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Caleidoscopio",
    description: "Simetría psicodélica.",
    filter: "hflip,vflip,tile=2x2",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Sueño borroso",
    description: "Efecto de fantasía.",
    filter: "split[a][b];[a]boxblur=20[a];[b][a]blend=all_mode=screen",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Fantasma",
    description: "Doble exposición temporal.",
    filter: "split[a][b];[b]setpts=PTS-0.3/TB[b];[a][b]blend=all_mode=screen",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Eco de movimiento",
    description: "Estelas de movimiento.",
    filter: "tmix=frames=5:weights='1 1 1 1 1'",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Fantasma RGB",
    description: "Movimiento con colores separados.",
    filter: "tblend=all_mode=average,chromashift=cbh=10:crh=-10",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Monitor CRT",
    description: "Pantalla vieja con líneas.",
    filter: "noise=alls=30,drawgrid=w=2:h=2:t=1",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Scanlines",
    description: "Líneas de monitor retro.",
    filter: "drawgrid=w=1:h=4:t=1",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Acuarela",
    description: "Efecto pintura.",
    filter: "gblur=sigma=5,eq=saturation=2",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Frames rotos",
    description: "Sensación de vídeo corrupto.",
    filter: "framestep=2,noise=alls=50",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Matrix verde",
    description: "Tinte verde digital.",
    filter: "colorchannelmixer=.3:0:.3:0:.3:0:.3:0:.3",
    category: CATEGORIES.FILTROS,
  },
  {
    title: "Espectro de audio",
    description: "Visualiza frecuencias del sonido.",
    filter: "showspectrum=s=hd720",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Desplazamiento de onda",
    description: "Deforma la imagen con ondas sinusoidales.",
    filter: "geq=r='p(X+20*sin(2*PI*Y/80+T*3),Y+15*sin(2*PI*X/120+T*2))':g='p(X+20*sin(2*PI*Y/80+T*3),Y+15*sin(2*PI*X/120+T*2))':b='p(X+20*sin(2*PI*Y/80+T*3),Y+15*sin(2*PI*X/120+T*2))'",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Posterizar",
    description: "Reduce los colores a tonos planos tipo póster.",
    filter: "lutrgb=r='floor(val/64)*64':g='floor(val/64)*64':b='floor(val/64)*64'",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Posterizar 3 colores",
    description: "Reduce la imagen a solo 3 colores.",
    filter: "elbg=codebook_length=3",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Diferencia de movimiento",
    description: "Resalta los cambios entre frames consecutivos.",
    filter: "[1:v]setpts=PTS+0.08/TB[shifted];[0:v][shifted]blend=all_mode=difference:all_opacity=1.0",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Enfocar bordes",
    description: "Realza los bordes de la imagen con convolución.",
    filter: "convolution='-2 -1 0 -1 1 1 0 1 2'",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Solarizar",
    description: "Invierte parcialmente los colores claros.",
    filter: "lutrgb=r='if(gte(val,128),255-val,val)'",
    category: CATEGORIES.FILTROS,
  },
  {
    title: "Noir",
    description: "Estilo cine negro con alto contraste.",
    filter: "hue=s=0,curves=strong_contrast",
    category: CATEGORIES.FILTROS,
  },
  {
    title: "Ojo de pez inverso",
    description: "Distorsión que expande el centro de la imagen.",
    filter: "lenscorrection=k1=-0.35:k2=0",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Blanco nuclear",
    description: "Brillo y contraste extremos.",
    filter: "eq=brightness=0.4:contrast=2",
    category: CATEGORIES.FILTROS,
  },
  {
    title: "Exposición larga",
    description: "Mezcla 50 frames como una exposición prolongada.",
    filter: "tmix=frames=50",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Time lapse",
    description: "Acelera el vídeo 50 veces.",
    filter: "setpts=0.02*PTS",
    category: CATEGORIES.EFECTOS,
  },
  {
    title: "Halation",
    description: "Resplandor suave alrededor de los bordes.",
    filter: "yaepblur=radius=15:sigma=256,vibrance=intensity=0.5",
    category: CATEGORIES.FILTROS,
  },
];

export default presets;
